Feature/notification for norewards nobonus discountbox
valkdigital/ui-kit pull request #114
Opened 2023-04-04 12:48 UTC by Joram3000

2023-04-05 07:05 UTC, Martijnme requested changes

2023-04-05 07:05 UTC, Martijnme commented on src/components/Book/overview/DiscountBox.tsx
> +      {rewards >= 0 && bonus >= 0 && (
Dit gehele component ff nalopen. Is net als previous doorgenomen te optimaliseren doordat er veel de zelfde props types worden aangeroepen

2023-04-05 08:52 UTC, Joram3000 commented on src/components/Book/BookOverview.tsx
> +  noBonusNoLoyal?: string;
ja deze is zeker nodig. Dit is een translation voor de message. Die wordt gebrukt op de Discountpicker.
Aangezien deze translation (voorlopig) nog niet nodig is voor ValkWork heb ik er een ? achter gezet :)

2023-04-05 09:08 UTC, Joram3000 commented on src/components/Book/overview/DiscountBox.tsx
> +      {rewards >= 0 && bonus >= 0 && (
ik heb de andere branch erin gemerged en ook een betere conditie geschreven..

2023-04-06 08:07 UTC, Martijnme requested changes

2023-04-06 08:07 UTC, Martijnme commented on src/components/Book/overview/DiscountBox.tsx
> +          <DiscountPicker
Je maakt nu 3x gebruik van dezelfde structuur, dit kan je doormiddel van een loopje optimaliseren.

```
<View style={styles.row}>
          <Text>
            {translations.loyalBalance} <-- translation for balance

            <Pressable hitSlop={hitSlop} onPress={showValkLoyalInfo}>
              <Icon
                name="information"
                size="small"
                style={styles.infoIcon}
                color={info.primary}
              />
            </Pressable>
          </Text>

          <DiscountPicker
            available={loyal} < -- value
            payable={payable}
            value={loyalUse} < -- use value
            title={"Valk Loyal"}
            setValue={onSetLoyal} < -- set value
          />
        </View>
```

2023-04-06 08:07 UTC, Martijnme commented on example/yarn.lock
>      domutils "^2.6.0"
je hebt waarschijnlijk in j IOS folder `yarn install` gedaan, deze kan weg

2023-04-06 08:07 UTC, Martijnme commented on src/components/Book/overview/DiscountBox.tsx
>        )}
Loop sowieso heel dit component ff na, je verplaatst nu het probleem naar één niveau hoger. Dit kan meer generiek geschreven worden, door het bijvoorbeeld 3x aan te roepen ipv alles in 1. Ook was afgesproken geen volledige objecten mee te geven `translations: BookOverviewTranslations;` Alleen wat je echt nodig hebt graag meegeven

2023-04-06 11:33 UTC, Joram3000 commented on src/components/Book/BookOverview.tsx
> +  noBonusNoLoyal?: string;
<img width="633" alt="image" src="https://user-images.githubusercontent.com/98752947/230364821-52a03db8-e4b2-491d-8d1b-653a7467e61c.png">
deze translation key wordt gebruikt door DiscountBox. Hij is optional ivm Valkwork. Daar hebben geen Bonus en Rewards

2023-04-06 11:34 UTC, Joram3000 commented on src/components/Book/overview/DiscountBox.tsx
> +          <DiscountPicker
nee slechts 2x. Rewards en Loyal. Bonus werkt anders

2023-04-06 11:44 UTC, Joram3000 commented on src/components/Book/overview/DiscountBox.tsx
>        )}
hoe bedoel je precies met 1 niveau hoger? k heb met lars besproken hoe dit te doen namelijk :)

2023-04-07 09:54 UTC, Joram3000 commented on example/yarn.lock
>      domutils "^2.6.0"
alles is resolved behalve deze. 

yarn lock weggegooid. nu Yarnt ie niet lekker.

2023-04-11 13:58 UTC, Joram3000 commented on example/yarn.lock
>      domutils "^2.6.0"
opnieuw gecreeerd, lijkt nu allemaal goed te zijn

2023-04-11 15:20 UTC, Martijnme approved these changes

2023-04-12 08:14 UTC, merged