gamesave
valkdigital/ui-kit pull request #115
Opened 2023-04-05 07:57 UTC by Joram3000

2023-04-24 09:30 UTC, Infigoforza requested changes
Echt beter de documentatie van o.a. Flatlist lezen...

2023-04-24 09:30 UTC, Infigoforza commented on example/storybook/stories/CardsNew.tsx
Maak ook nog een story aan voor web, zodat ze terug komen op:
https://valkdigital.github.io/ui-kit/?path=/story/booking-engine--book-availability

2023-04-24 09:30 UTC, Infigoforza commented on src/components/Cards/SmallHorizontalListCardNew.tsx
SmallHorizontalCard.tsx

2023-04-24 09:30 UTC, Infigoforza commented on src/components/Cards/VerticalCardGrid.tsx
> +      keyExtractor={(item) => item}
Dit is niet hoe dat moet... 
https://reactnative.dev/docs/flatlist#keyextractor

2023-05-01 10:01 UTC, Joram3000 commented on src/components/Cards/SmallHorizontalListCardNew.tsx
> +  kmLabel?: string;
heb nu 2 labels ( topLeft en bottomRight ) va

2023-05-01 10:04 UTC, Joram3000 commented on src/components/Cards/VerticalCardGrid.tsx
> +    horizontal
![image](https://user-images.githubusercontent.com/98752947/235438398-2eae6039-5f0d-4166-b5d4-64fb93f3dcb9.png)

in de uitwerking is het een vertical list card al zit er idd wat horizontal scrolling op , ik kan hem hernoemen maar dan krijgen we discrepantie met UXUI

2023-05-01 10:08 UTC, Joram3000 commented on src/components/Cards/SmallHorizontalListCardNew.tsx
> +  kmLabel?: string;
misschien moet bottomRight hernoemt worden naar distanceLabel ?

2023-05-09 15:18 UTC, closed without merging