Feature/vertical list card and storybook
valkdigital/ui-kit pull request #122
Opened 2023-05-03 11:03 UTC by Joram3000

2023-05-10 07:13 UTC, mrjln commented on example/storybook/stories/CardsNew.tsx
> +const CardsNew: React.FC = () => (
Heet het nieuwe component CardsNew? 
Naam zegt mij niks, wat voor een kaart is het?

2023-05-10 07:40 UTC, Joram3000 commented on example/storybook/stories/CardsNew.tsx
> +const CardsNew: React.FC = () => (
ja dit is alleen de nieuwe story  (iets minder belangrijk)
maar ik zou em nog kunnen hernoemen naar NewCardsStory ?

2023-05-10 10:58 UTC, Joram3000 commented on example/storybook/stories/CardsNew.tsx
> +const CardsNew: React.FC = () => (
hernoemd

2023-05-17 07:54 UTC, mrjln commented on src/components/Cards/SmallHorizontalCard.tsx
> +    cardWidth = 154,
Waarom is het nodig om deze props te hebben als je ze overschrijft met default waardes? 
Zijn er use cases waarbij de cardWidth of imgHeight aangepast moet kunnen worden?

2023-05-17 07:55 UTC, mrjln commented on src/components/Cards/SmallHorizontalCard.tsx
> +    backgroundColor: "#DCDCDC",
Nog veranderen in een theme kleur. Iets van `light.background` ofzoiets

2023-05-17 07:56 UTC, mrjln commented on src/components/Cards/common/BaseCard.tsx
> +              blurRadius: shadowBlurRadius === undefined ? 8 : shadowBlurRadius,
`!shadowBlurRadius`  ?

2023-05-17 07:57 UTC, mrjln commented on src/components/input/SegmentedInput/index.tsx
> +        if (delay.current && typeof delay.current !== "number")
Waarom was dit nodig?

2023-05-17 07:58 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +const GridArray = testData.reduce((result: any, item, index) => {
Geen hoofdletter :)

2023-05-17 07:59 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +console.log({ GridArray });
console.log

2023-05-17 07:59 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +const GridArray = testData.reduce((result: any, item, index) => {
`result` kan nog netjes getypt. `any` are you OK?

2023-05-17 08:02 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +const GridArray = testData.reduce((result: any, item, index) => {
netjes dat je een reduce gebruikt hebt 👍

2023-05-17 08:03 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +const NewCardsStories: React.FC = () => {
Kan dit niet gewoon `CardStories` heten?

2023-05-17 08:05 UTC, mrjln commented on example/storybook/stories/NewCardsStories.tsx
> +const GridArray = testData.reduce((result: any, item, index) => {
Je zou er zelfs een helper functie van kunnen maken, dat iedereen deze functionaliteit kan hergebruiken als je jouw array aan data netjes in chunks van 3 wilt opsplitsen.

2023-05-17 08:10 UTC, mrjln requested changes
Nog een paar vragen en puntjes op de i

2023-05-17 13:16 UTC, Joram3000 commented on example/storybook/stories/NewCardsStories.tsx
> +const GridArray = testData.reduce((result: any, item, index) => {
helper functie gemaakt,hoofdletter weg, functie verbeterd, alleen die result blijft een any hebben

2023-05-17 13:25 UTC, Joram3000 commented on src/components/input/SegmentedInput/index.tsx
> +        if (delay.current && typeof delay.current !== "number")
![image](https://github.com/valkdigital/ui-kit/assets/98752947/7f0ddfa8-7330-49f5-9d86-f2fdcc121074)
om dit weg te werken, volgens mij iets wat ik met lars had opgelost als ik me goed herinner , moet ik et weer terugdraaien?

2023-05-17 13:29 UTC, Joram3000 commented on src/components/Cards/SmallHorizontalCard.tsx
> +    cardWidth = 154,
ja leek me prettig dynamisch te hebben afhankelijk van evt content format changes, zal ik het als waarde verwerken ipv als prop?

2023-05-17 14:02 UTC, mrjln commented on src/components/input/SegmentedInput/index.tsx
> +        if (delay.current && typeof delay.current !== "number")
Nee is goe! Was gewoon benieuwd :)

2023-05-22 08:02 UTC, mrjln commented on src/components/Cards/SmallHorizontalCard.tsx
> +    cardWidth = 154,
Allrighty

2023-05-22 08:12 UTC, mrjln approved these changes
Nice changes, LGTM 🆗

2023-05-22 08:26 UTC, merged