Edit button carrousel
valkdigital/ui-kit pull request #140
Opened 2023-05-30 14:49 UTC by Martijnme

2023-06-13 08:19 UTC, MarsTwix requested changes

2023-06-13 08:19 UTC, MarsTwix commented on src/components/Button/ButtonCarrousel.tsx
> +              width: tileWidth,
Hier dan een prop voor meegeven tileIconWidth en tileIconHeight

2023-06-13 08:19 UTC, MarsTwix commented on src/components/Cards/SmallHorizontalListCard.tsx
> +      <View>
Wat doet deze view nou precies? Anders kan die toch gewoon weggelaten worden?

2023-06-13 08:46 UTC, mrjln commented on src/components/Button/ButtonCarrousel.tsx
> +const ButtonCarrousel: FC<ButtonCarrouselProps> = ({
Bestond de ButtonCarousel al? En zo ja, waar gebruiken we die? 
Want anders isie nu ineens goud :D

2023-06-13 10:25 UTC, Martijnme commented on src/components/Button/ButtonCarrousel.tsx
> +const ButtonCarrousel: FC<ButtonCarrouselProps> = ({
Het is een Carrocel van buttons. niet alleen de carrousel

2023-06-13 10:26 UTC, mrjln commented on src/components/Button/ButtonCarrousel.tsx
> +const ButtonCarrousel: FC<ButtonCarrouselProps> = ({
Bueno

2023-06-13 10:29 UTC, Martijnme commented on src/components/Button/ButtonCarrousel.tsx
> +const ButtonCarrousel: FC<ButtonCarrouselProps> = ({
Het is een Carrousel van buttons. ButtonCarrousel

2023-06-13 10:34 UTC, Martijnme commented on src/components/Cards/SmallHorizontalListCard.tsx
> +      <View>
Om de size van de image als absolute aan te houden ipv de size van de algemene container

2023-06-13 10:40 UTC, Martijnme commented on example/assets/fonts/OpenSans-Bold.ttf
Gezien het een `+` file is. lijkt mij dat dit lost in translation is geraakt door een vorige merge

2023-06-16 12:26 UTC, mrjln approved these changes
👍

2023-06-16 12:51 UTC, MarsTwix approved these changes

2023-06-16 12:53 UTC, merged