replace' replaceAll' to 'replace with /g tag'
valkdigital/ui-kit pull request #182
Opened 2023-07-25 09:39 UTC by Joram3000

Er was een bug op android {replaceAll is not a function}
daardoor kon ik em niet bouwen op android

met deze fix zou alles weer naar behoren moeten zijn.

2023-08-01 15:16 UTC, mrjln commented
Okey, ik snap dat het een kleine fix is, maar ik snap de uitleg niet helemaal. 
.replaceAll is een nieuwere javascript functie, die inmiddels hele goeie compatibility heeft: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility 

Dus kan je nog even uitzoeken waarom het bij jou niet werkt? 
Werkt het bij andere mensen ook niet? 
Heb je gecheckt of het aan de node-versie ligt? 

Het heeft in iedergeval niks met android te maken, als het goed is.

2023-08-01 15:23 UTC, mrjln requested changes
zie comment!

2023-08-02 09:05 UTC, Martijnme commented
ipv `replaceAll(" ", "")` kan je ook `replace(/\s/g, “”)` gebruiken

2023-08-02 10:39 UTC, mrjln commented
> ipv `replaceAll(" ", "")` kan je ook `replace(/\s/g, “”)` gebruiken

Dat is toch precies wat Joram heeft gedaan? ^_^

2023-08-02 11:40 UTC, Joram3000 commented
![image](https://github.com/valkdigital/ui-kit/assets/98752947/a7cd0b25-41da-442b-9e2f-4b341b249acb)
dit is wat ik krijg als ik op android build vanaf main

2023-08-02 12:01 UTC, mrjln approved these changes

2023-08-02 14:03 UTC, merged