remove icon converter from prepare
valkdigital/ui-kit pull request #183
Opened 2023-07-25 09:45 UTC by Joram3000

ik heb de icon converter van de prepare afgehaald want bij elke yarn ging dat ding alle icoontjes totaal voor niets nog eens langslopen.

2023-07-25 11:45 UTC, Martijnme requested changes

2023-07-25 11:45 UTC, Martijnme commented on package.json
> +    "prepare": "bob build",
misschien de readme nog ff aanvullen met instructies

2023-07-25 14:09 UTC, Joram3000 commented on package.json
> +    "prepare": "bob build",
gedaan :)

2023-07-26 09:00 UTC, Martijnme approved these changes

2023-07-26 13:07 UTC, merged