Feat/notifications and storybook
valkdigital/ui-kit pull request #216
Opened 2023-11-30 16:15 UTC by mrjln

2023-12-05 13:11 UTC, Infigoforza requested changes
Ziet er al goed uit!  Lekker bezig 🎉 

Mis alleen nog het stukje van het deployen van de nieuwe storybook. 
idealiter naast de oude storybook die nu gedeployed staat. Aangezien we nog niet alles hebben overgezet naar de nieuwe stories en dan niet meer makkelijk kunnen zien welke component we hebben.

2023-12-05 13:12 UTC, Infigoforza commented
Zie nog wel wat conflicts, dus zou nog main hierin mergen voordat je deze gaat mergen :)

2023-12-08 09:21 UTC, Infigoforza requested changes
Nog een kleine opmerking, verder ziet het er goed uit 👍

2023-12-13 09:24 UTC, Infigoforza approved these changes
Je kan evenuteel example-ui-kit-vdvalk weer renamen naar example. 

Verder ziet het er goed uit (vergeet niet om main er in te mergen, voordat je dit merged naar main).

2024-01-31 10:36 UTC, Infigoforza commented on src/components/Book/availability/RateListItem.tsx
> +      {!isArrangement && type === "st" && cancellationPolicy ?
Deze conditional is nu anders, is dat de bedoeling?

2024-01-31 10:38 UTC, Infigoforza requested changes
1 vraagje, verder ziet het er goed uit.

2024-02-05 08:41 UTC, mrjln commented on src/components/Book/availability/RateListItem.tsx
> +      {!isArrangement && type === "st" && cancellationPolicy ?
Ik heb alleen de onnodige `<> ` en `</>` weggehaald

2024-02-05 08:42 UTC, mrjln commented on src/components/Book/availability/RateListItem.tsx
> +      {!isArrangement && type === "st" && cancellationPolicy ?
Wacht ik zie het nu.

2024-02-05 08:44 UTC, mrjln commented on src/components/Book/availability/RateListItem.tsx
> +      {!isArrangement && type === "st" && cancellationPolicy ?
Ik heb het terug gezet

2024-02-06 08:46 UTC, Infigoforza commented on package.json
> +    "storybook": "cd example && yarn && yarn start",
Klopt dit?

2024-02-12 14:42 UTC, mrjln commented on package.json
> +    "storybook": "cd example && yarn && yarn start",
Gecheckt en het klopt :)

2024-02-12 15:06 UTC, Infigoforza approved these changes

2024-02-12 15:09 UTC, merged