Feature/booking
valkdigital/ui-kit pull request #49
Opened 2022-10-25 09:54 UTC by MarsTwix

2022-11-07 08:44 UTC, jrnk requested changes

2022-11-07 08:44 UTC, jrnk commented on example/storybook/stories/BookOverviewStory.tsx
> +  const personsString = (adults: number, children: number, infants: number) => {
waarom is deze nodig op de story? die hoort in een helper (als het bij meerdere componenten wordt gebruikt dan in een `utils/formatPersons.ts` bijv)

2022-11-07 08:44 UTC, jrnk commented on example/storybook/stories/BookOverviewStory.tsx
> +  const totaalPrijs = kamerpijs + borgprijs + ontbijtPrijs + Toeristenbelasting;
Altjid engels gebruiken, geen nederlands voor variabelen e.d.

2022-11-07 08:44 UTC, jrnk commented on src/components/book/overview/DiscountBox.tsx
> +    Alert.alert("Valk Loyal", translations.loyalInfo);
is dit de bedoeling zo?

2022-11-07 08:44 UTC, jrnk commented on src/components/book/overview/PriceBox.tsx
> +  getPriceOfChosenExtraAndGetCorrespondingExtraHelper?: (
Deze method naam is veel te Java. `getPriceAndHelper` is prima, je zit al in die component book namespace

2022-11-10 19:21 UTC, MarsTwix commented on src/components/book/overview/DiscountBox.tsx
> +    Alert.alert("Valk Loyal", translations.loyalInfo);
Ja dit klopt! Dit komt van VEX. De bedoeling hiervan is, dat er i knoppen zijn waarop je kan drukken voor meer info

2022-11-10 19:22 UTC, MarsTwix commented on example/storybook/stories/BookOverviewStory.tsx
> +  const personsString = (adults: number, children: number, infants: number) => {
Ik heb hem gemoved naar hooks. Dat zijn in ui-kit de helpers/utils

2022-11-10 19:22 UTC, MarsTwix commented on example/storybook/stories/BookOverviewStory.tsx
> +  const totaalPrijs = kamerpijs + borgprijs + ontbijtPrijs + Toeristenbelasting;
Dit klopt inderdaad niet

2022-11-10 19:27 UTC, MarsTwix commented on src/components/book/overview/PriceBox.tsx
> +  getPriceOfChosenExtraAndGetCorrespondingExtraHelper?: (
Ik heb hem veranderd naar `getPriceAndCorresponding`. Is dat ook oke?

2022-12-12 19:53 UTC, Stewie02 requested changes

2022-12-12 19:53 UTC, Stewie02 commented on src/components/Cards/common/CardLabel.tsx
>    if (labelColor === undefined) labelColor = brightGold.primary;
Was het doel om de CardLabel ook te veranderen qua style of is dit puur refactoren?

2022-12-12 19:53 UTC, Stewie02 commented on src/components/book/overview/DiscountBox.tsx
> +  analyticsLogEvent?: (
Ik weet niet of dit de beste optie is voor in de UI-kit. Beter lijkt mij bijvoorbeeld
  onToggleLoyalUse: () => void;

Voor de UI-kit maakt het niet uit of die actie nou een analytics event is of dat iets anders getriggerd wordt. Nu bouw je dat een beetje dicht. Het gebeurt vaker dus je moet al je changes even checken

2022-12-12 19:53 UTC, Stewie02 commented on src/hooks/useMoneyFormatter.tsx
> +};
Is geen hook, is gewoon een helper. Dus geen useNogWattes gebruiken

2022-12-12 19:53 UTC, Stewie02 commented on src/hooks/useDateFormatter.tsx
>  }
Is geen hook, gewoon een simpele helper

2022-12-12 19:53 UTC, Stewie02 commented on src/hooks/usePersonsFormatter.tsx
> +  return personsLine;
Wordt alleen maar in storybook gebruikt, dan hoeft deze niet buiten de storybook folder te staan

2022-12-14 20:19 UTC, MarsTwix commented on src/components/Calendar.tsx
>  import { Calendar, DateObject } from "react-native-calendars";
Anders krijg je de error `Module '"react-native-calendars"' has no exported member 'DateObject'.`

2022-12-14 20:20 UTC, MarsTwix commented on src/components/Cards/common/CardLabel.tsx
>    if (labelColor === undefined) labelColor = brightGold.primary;
Ja dit was een refactor suggestie van Jeroen

2022-12-17 14:02 UTC, MarsTwix commented on example/storybook/stories/BookOverviewStory.tsx
> +        meal_price: breakfastPrice,
Dit heeft er mee te maken, dat het in VEX zo staat. Het aanpassen in VEX naar camelCase zorgt ervoor dat de api de variable niet meer herkent

2022-12-20 07:37 UTC, Stewie02 commented on src/components/Calendar.tsx
>  import { Calendar, DateObject } from "react-native-calendars";
Dan bestaat hij gewoon niet, is het niet DateData?

2022-12-21 08:28 UTC, Stewie02 approved these changes

2022-12-29 08:40 UTC, merged