Feature/bold label
valkdigital/ui-kit pull request #54
Opened 2022-11-07 20:13 UTC by MarsTwix

2022-11-07 20:18 UTC, Stewie02 commented on src/components/Cards/VerticalListCard.tsx
>      flex: 1,
Wordt deze card op meerdere plekken gebruikt in de apps of alleen bij de vouchers en is styling gewoon veranderd? Als hij meer wordt gebruikt moet je nog even checken of de styling overal aangepast mag worden

2022-11-07 20:18 UTC, Stewie02 commented on src/components/Cards/common/CardLabel.tsx
> -        type="subtextRegular"
Zie vorige comment

2022-11-07 20:18 UTC, Stewie02 commented on src/components/Cards/common/CardText.tsx
>  const CardSubHeaderText: React.FC<TextProps> = (props) => {
^^

2022-11-09 18:49 UTC, MarsTwix commented on src/components/Cards/VerticalListCard.tsx
>      flex: 1,
Ja dit wordt alleen bij de vouchers gebruikt

2022-11-09 19:29 UTC, MarsTwix commented on src/components/Cards/common/CardText.tsx
>  const CardSubHeaderText: React.FC<TextProps> = (props) => {
Deze klopt nog steeds volgens figma

2022-11-09 19:29 UTC, MarsTwix commented on src/components/Cards/common/CardLabel.tsx
> -        type="subtextRegular"
Hierin heb ik wel aanpassingen gemaakt

2022-11-10 17:56 UTC, Stewie02 requested changes

2022-11-10 17:56 UTC, Stewie02 commented on src/components/Cards/common/CardLabel.tsx
> +      </Text>
Wat gebeurt er als je label en boldLabel meegeeft inclusief small=true? Dan wordt boldLabel helemaal genegeerd of niet? EDIT: Volgens mij kan dit hele component wel anders, heb jij vanavond rond 21:15 a 21:30 tijd om te bellen?

2022-11-10 17:56 UTC, Stewie02 commented on src/components/Cards/common/CardText.tsx
>  const CardSubHeaderText: React.FC<TextProps> = (props) => {
Maar op andere plekken wordt het niet gebruikt? Zo niet, dan mag je gewoon de conversation closen! 😄

2022-11-12 11:08 UTC, merged