Feature/reservation status implementation
valkdigital/ui-kit pull request #60
Opened 2022-12-27 12:45 UTC by MarsTwix

2022-12-28 10:22 UTC, Infigoforza commented on src/components/book/ReservationStatus.tsx
> +import { Button, Icon, Spacing, Text, ThemeContext } from "@valkdigital/ui-kit";
Moet deze import niet naar een locale path, 
Zoals op regel 5

2022-12-28 10:22 UTC, Infigoforza commented on src/Loader.tsx
> +import { Text } from "@valkdigital/ui-kit";
import naar locale path

2022-12-28 10:23 UTC, Infigoforza commented on src/components/book/ReservationStatus.tsx
> +
Gekke witregels, werkt je formatter wel?

2022-12-28 10:24 UTC, Infigoforza commented on src/components/book/ReservationStatus.tsx
> +  translations: Record<string, any>;
Zou dit wel type, anders weet ik niet welke translations je allemaal verwacht.

2022-12-28 10:27 UTC, Infigoforza commented on src/components/book/ReservationStatus.tsx
> +  translations: Record<string, any>;
En zou het object flatten, nu heb je bijv  translations.reservation.successRequestheader. 
Ik zou er gewoon translations.successRequestHeader van maken.

2022-12-28 10:28 UTC, Infigoforza reviewed
Heb nog wel wat kleine puntjes, ook misschien handig om het te draaien in storybook.

2022-12-28 10:29 UTC, Infigoforza requested changes
Zie comments

2023-01-06 11:38 UTC, Infigoforza commented on src/components/Reservation.tsx
>      width: "100%",
liever geen percentages, maar align-self: "stretch"

2023-01-06 11:40 UTC, Infigoforza commented on src/components/book/ReservationStatus.tsx
> +
Nog steeds gekke witregels

2023-01-06 11:42 UTC, Infigoforza requested changes
Je heb nog niet alle feedback van de vorige keer verwerkt

2023-01-15 14:37 UTC, MarsTwix commented on src/components/book/ReservationStatus.tsx
> +
Huh, dat is wel gek. Ik gebruik namelijk gewoon prettier en voor mij werkt het prima

2023-01-19 14:34 UTC, merged