Feature/choiceline migration
valkdigital/ui-kit pull request #78
Opened 2023-02-16 08:58 UTC by Joram3000

inc juiste imports

2023-02-21 07:23 UTC, Stewie02 requested changes

2023-02-21 07:23 UTC, Stewie02 commented on example/storybook/stories/index.tsx
> +ReservationStories.add("Reservation status canceled", () => (
Cancelled***, check de hele file eventjes voor deze taalfout

Marnix weet hoe je een spelchecker kunt installeren in VSCode zodat het niet meer fout zal gaan in de toekomst 😄

2023-02-21 07:23 UTC, Stewie02 commented on example/storybook/stories/index.tsx
> +    <ChoiceLine label="ontbijt" value="doe maar" />
Dit lijken mij niet hele goede labels/values, ook niet voor storybook

2023-02-21 07:23 UTC, Stewie02 commented on src/components/Reservation/Choiceline.tsx
> +    minHeight: 64,
Spacing.sp8

2023-02-21 07:23 UTC, Stewie02 commented on src/components/Reservation/Choiceline.tsx
> +    marginRight: 40,
Spacing.sp5

2023-02-21 07:23 UTC, Stewie02 commented on src/index.ts
> +// Reservationcomponents
reservation components

2023-02-21 08:08 UTC, Joram3000 commented on example/storybook/stories/index.tsx
> +ReservationStories.add("Reservation status canceled", () => (
Dat is iets wat Marnix heeft geschreven geloof ik

2023-02-23 15:02 UTC, Joram3000 commented on src/components/Reservation/Choiceline.tsx
> +    marginRight: 40,
deze kan ik nog even meenmen in de volgende ronde

2023-04-05 07:52 UTC, closed without merging