import new elements
valkdigital/ui-kit pull request #81
Opened 2023-02-21 08:05 UTC by Joram3000

WIP

2023-03-23 16:14 UTC, jrnk requested changes
Top! Paar opmerkingen maar.

2023-03-23 16:14 UTC, jrnk commented on src/components/Parallax.tsx
> +let HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT;
Dit zijn alle 3 `const` (ze veranderen niet meer)

2023-03-23 16:14 UTC, jrnk commented on src/components/Parallax.tsx
> +  children?: JSX.Element | React.ReactNode;
`React.ReactNode` volstaat

2023-03-23 16:14 UTC, jrnk commented on src/components/Parallax.tsx
> +      // iOS offset for RefreshControl
Waarom is dit dan niet iOS only?

2023-03-23 16:14 UTC, jrnk commented on src/components/PhotoViewer/ZoomablePhotoViewer.tsx
> +    });
Waarschijnlijk hoort dit niet bij de PR, maar dit shared niet de image zelf maar een link naar de image? Niet echt useful op deze manier.

2023-03-23 16:14 UTC, jrnk commented on src/components/Photoslider.tsx
> +  const [cardWidth, setCardWidth] = useState(0);
deze mogen ook nog typed `useState<number>(0)`

2023-03-23 16:14 UTC, jrnk commented on src/components/Photoslider.tsx
> +            right: 0,
kun je deze als `style={[style.gradient, {height: imageHeight}]` doen met een definitie in de StyleSheet onderaan? Zodat die `LinearGradient` eronder er ook van profiteert?

2023-03-23 16:23 UTC, Joram3000 commented on src/components/Parallax.tsx
> +  children?: JSX.Element | React.ReactNode;
dat werkt helaas niet , vermoedelijk omdat een ReactNode ook null kan zijn..

2023-03-23 16:25 UTC, Joram3000 commented on src/components/Parallax.tsx
> +let HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT;
HEADER_MIN_HEIGHT wel

2023-03-23 20:57 UTC, jrnk requested changes
Mini `let` dingetje nog. Zie nu dat we hier de styling nog niet hebben overgenomen zoals bij de andere projecten, maar deze commit hanteert weer andere code styling dan je vorige commits (trailing semicolon o.a.) dus daar even op letten.

2023-03-23 20:57 UTC, jrnk commented on src/components/Parallax.tsx
>  let HEADER_MIN_HEIGHT = Platform.OS === "android" ? 56 : 88;
same hier

2023-03-27 09:42 UTC, Joram3000 commented on src/components/Parallax.tsx
>  let HEADER_MIN_HEIGHT = Platform.OS === "android" ? 56 : 88;
deze moet let zijn ivm 
regel 78  HEADER_MIN_HEIGHT = useNativeHeaderHeight();

2023-03-27 09:47 UTC, Joram3000 commented on src/components/PhotoViewer/ZoomablePhotoViewer.tsx
> +    });
Ik heb hier een nieuwe click up taak voor aangemaakt

2023-03-28 07:36 UTC, jrnk requested changes

2023-03-28 07:36 UTC, jrnk commented on src/components/Parallax.tsx
> +let HEADER_MIN_HEIGHT = Platform.OS === "android" ? 56 : 88
dient ook een `const` te zijn

2023-03-28 09:06 UTC, jrnk commented on src/components/Parallax.tsx
> +let HEADER_MIN_HEIGHT = Platform.OS === "android" ? 56 : 88
Als je hem daar set hoort het geen const te zijn, maar die dient dan ook niet als een all-caps `const` te worden gedefinieerd. Als je hem reset naar die hoogte van `useNativeHeaderHeight` dien je hem niet te gebruiken in die berekening daarboven als iets wat 'vast' staat.

2023-03-28 13:44 UTC, merged