Add usage to readme
valkdigital/ui-kit pull request #96
Opened 2023-03-14 13:40 UTC by Martijnme

2023-03-15 09:40 UTC, Stewie02 requested changes

2023-03-15 09:40 UTC, Stewie02 commented on README.md
> +
Nog toevoegen dat niet hele type meegegeven mogen worden, bijvoorbeeld `room` en dat een kamer card bijvoorbeeld name, price props krijgen

2023-03-22 08:37 UTC, Infigoforza approved these changes

2023-03-22 08:46 UTC, Stewie02 commented on README.md
> +When testing a component, the prefix old<componentName> and new<componentName> are used.
Old<ComponentName> and New<ComponentName>

2023-03-29 11:07 UTC, merged