Feature/upgrade icons to svg
valkdigital/ui-kit pull request #97
Opened 2023-03-14 15:17 UTC by Joram3000

2023-03-15 09:30 UTC, Infigoforza requested changes
Nog een paar kleine punten

2023-03-15 09:34 UTC, Joram3000 commented on src/components/Icon.tsx
> +  // @ts-ignore
dat is die ene die we der neerzette voor dit: 
![image](https://user-images.githubusercontent.com/98752947/225268217-66ca7040-2642-4332-a658-61d1ea485354.png)

2023-03-15 10:07 UTC, Joram3000 commented on src/components/Icon.tsx
![image](https://user-images.githubusercontent.com/98752947/225276904-7ca0dba9-e7e2-4c44-ac64-96f2f8c1779d.png)

2023-03-17 09:39 UTC, jrnk requested changes
nvm ik mistte iets :D

2023-03-17 09:39 UTC, jrnk commented on src/media/icons/outlineSVG/index.ts
> +export { default as ActionsHorizontal } from "./ActionsHorizontal";
`export * from "./ActionsHorizontal";` zou voldoende moeten zijn per component omdat je al een "export default" in de componenten zelf hebt

2023-03-17 09:47 UTC, Infigoforza commented on src/components/Icon.tsx
> +  // @ts-ignore
Ja, "prima" om een @ts-ignore te gebruiken om tijdens het dev even snel iets te testen of het werkt. 
Maar ik zei ook de typing fixen en niet laten staan voordat je een code review aanvraagt...

2023-03-20 08:42 UTC, Joram3000 commented on src/components/Icon.tsx
> +  // @ts-ignore
excuus zal zo wegwerken.

2023-03-20 09:23 UTC, Joram3000 commented on src/media/icons/outlineSVG/index.ts
> +export { default as ActionsHorizontal } from "./ActionsHorizontal";
helaas niet. had zojuist geprobeerd maar krijg dan een volgende error 
property "this" does not exist on type typeof

2023-03-22 10:51 UTC, jrnk approved these changes

2023-03-28 13:43 UTC, merged